### PR TITLE
Error installing the xlwt-future

### PR DESCRIPTION
**Pull request by goinnn**
If I try to install xlwt-future I get an error:

```
 pip install git+https://github.com/PythonCharmers/xlwt-future.git#egg=xlwt

Downloading/unpacking xlwt from git+https://github.com/PythonCharmers/xlwt-future.git                                                                                                                                           
Cloning https://github.com/PythonCharmers/xlwt-future.git to /home/pmartin/git-projects/django-tables2-repots-polaco/django-tables2-reports/.tox/py33-dj15/build/xlwt                                                         
Running setup.py egg_info for package xlwt                                                                                                                                                                                    
    Traceback (most recent call last):                                                                                                                                                                                          
    File "<string>", line 16, in <module>                                                                                                                                                                                     
    File "/home/pmartin/git-projects/django-tables2-repots-polaco/django-tables2-reports/.tox/py33-dj15/build/xlwt/setup.py", line 4, in <module>                                                                             
        from xlwt import __VERSION__                                                                                                                                                                                            
    File "./xlwt/__init__.py", line 4, in <module>                                                                                                                                                                            
        from .Workbook import Workbook                                                                                                                                                                                          
    File "./xlwt/Workbook.py", line 44, in <module>                                                                                                                                                                           
        from . import BIFFRecords                                                                                                                                                                                               
    File "./xlwt/BIFFRecords.py", line 6, in <module>                                                                                                                                                                         
        from .UnicodeUtils import upack1, upack2, upack2rt                                                                                                                                                                      
    File "./xlwt/UnicodeUtils.py", line 45, in <module>                                                                                                                                                                       
        from future.builtins import *                                                                                                                                                                                           
    ImportError: No module named 'future'                                                                                                                                                                                       
    Complete output from command python setup.py egg_info:                                                                                                                                                                      
    Traceback (most recent call last):                                                                                                                                                                                          

File "<string>", line 16, in <module>                                                                                                                                                                                         

File "/home/pmartin/git-projects/django-tables2-repots-polaco/django-tables2-reports/.tox/py33-dj15/build/xlwt/setup.py", line 4, in <module>                                                                                 

    from xlwt import __VERSION__                                                                                                                                                                                                

File "./xlwt/__init__.py", line 4, in <module>                                                                                                                                                                                

    from .Workbook import Workbook                                                                                                                                                                                              

File "./xlwt/Workbook.py", line 44, in <module>                                                                                                                                                                               

    from . import BIFFRecords                                                                                                                                                                                                   

File "./xlwt/BIFFRecords.py", line 6, in <module>                                                                                                                                                                             

    from .UnicodeUtils import upack1, upack2, upack2rt                                                                                                                                                                          

File "./xlwt/UnicodeUtils.py", line 45, in <module>                                                                                                                                                                           

    from future.builtins import *                                                                                                                                                                                               

ImportError: No module named 'future'      
```

### CODE REVIEW

**Comment by edschofield** [comment]
Hi Pablo,

Thanks very much for the pull request. It has highlighted a couple of other problems too. I'm in the process of fixing these now...

**Comment by goinnn** [comment]
@edschofield Thanks!

**Comment by edschofield** [comment]
Oops, it seems distutils doesn't support install_requires::

```
(xlwt_env)user@pythoncharmers:~/Code/xlwt$ python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
```

It might be time for an upgrade to setuptools. (The original xlwt didn't need it because it didn't have any dependencies.)

**Comment by goinnn** [comment]
@edschofield works on my machine... :-(

But if with distutils this does not works remove this line (install_requires)

**Pull request merged**
